### ISSUE TITLE
Considerations on CI strategy due to CI failures with very old or new R versions

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/r-hyperspec.github.io#10]
This error is from `hySpc.read.jdx` repo:

![image](https://user-images.githubusercontent.com/12725868/121716774-1eed7000-cae9-11eb-8b52-e7f53098cb03.png)

but it will arise in any package that depends on the development version of `hyperSpec` as binaries of this version are not present in our `drat` repo called `pkg-repo`. Some issues may also arise while installing from the source by using `remotes::instal_github()` as the source on GitHub does not contain some files (like .Rd ones) which we do not track. So there are some points to consider:

1) What CI strategy should we use?
   a) How many previous R versions should we use for the R CMD check? 
   b) For how many old R versions should we build `hyperSpec` binaries?
2) Use simpler code vs. start tracking helper files:
  a) Should we still git-ignore some helper files (like `.Rd` files) and create some more advanced code for CI procedures (which potentially run longer and make CI servers consume more energy);
  b) or start tracking the files and use `remotes::install_github()` for easier installation of `hyperSpec` (devel version).
  
 There might be some other solutions that I'm not currently aware of.

**Comment by GegznaV** [comment]
OK, I see that we do not build binaries for Windows and Mac at all, and the `drat` repo contains only source packages. And these source packages have all the files needed to build a complete R package. So the problem is likely not what I anticipated before.

I'll have to delve into this issue more deeply.

**Comment by GegznaV** [comment]
Current builds pass without fixing anything I wrote above:
![image](https://user-images.githubusercontent.com/12725868/125166951-b0aed280-e1a6-11eb-86a4-492b1424c8ec.png)

So now I think that the problem was somewhere else so I'll close this issue for now as irrelevant.

**Comment by bryanhanson** [comment]
Right now the windows R 3.6 build is commented out and that may be why the checks pass.  This is related to whether we want to support any R before 4.0 (on the Trello list).  I am working on this and will report at the next video meeting.

**Comment by bryanhanson** [comment]
Reactivated Windows + R 3.6 and all checks pass, must have been a transient issue.
