### ISSUE TITLE
Automating Updates to the GHA Workflows (Proposal for r-hyperspec/hyperSpec)

### ISSUE THREAD

**Issue by bryanhanson** [r-hyperspec/r-hyperspec.github.io#11]
It would be extremely nice to be able to automate as much as possible the updating of the GHA workflows (I say this having just done this manually, in conjunction with VG).

A big obstacle to doing this is the organization of `cbeleites/hyperSpec` -- the package itself is inside a folder called `hyperSpec`.  I propose that when `cbeleites/hyperSpec`  is moved to `r-hyperspec/hyperSpec` that we make the folder structure like all the other repos by eliminating the outer folder.  If we do this, then we can write a GHA/bash/R script that will deploy workflow updates to all repos when we trigger it. There are two files that are identical across all the repos except just slightly different in `cbeleites/hyperSpec` due to the different path. It would be nice to eliminate this special case.

**Comment by cbeleites** [comment]
I fully agree - this is a historic remainder of **hyperSpec** having all those parts that did not go into the CRAN package.

**Comment by bryanhanson** [comment]
OK, we'll plan on doing this then.

**Comment by bryanhanson** [comment]
This is related to #13

**Comment by bryanhanson** [comment]
Closing, as the concern about folder structure has been addressed, and the issue of automating updates in more fully addressed in #13
