### ISSUE TITLE
Update COTRIBUTING.md as hyperSpec was moved to new repo

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/r-hyperspec.github.io#20]
Some links https://github.com/cbeleites/hyperSpec must be changed into https://github.com/r-hyperspec/hyperSpec after moving the new package to a new repo.

@bryanhanson, can you take care of that?

**Comment by bryanhanson** [comment]
Will do later today.

**Comment by bryanhanson** [comment]
Closed via https://github.com/r-hyperspec/hyperSpec/commit/d3a2f08165ea876577eacbc1a2cd8257d2428841
