### ISSUE TITLE
Decide CI system and set branch protection

### ISSUE THREAD

**Issue by cbeleites** [r-hyperspec/r-hyperspec.github.io#7]
- [X] decide CI system: we'll use github actions only
- [ ] protect develop branch

**Comment by GegznaV** [comment]
I think, that Travis CI and Appveyor should not be used anymore in favor of GH Actions. The minutes are counted only if on private but not on public repos (I tested that on my personal organization).

In some situations, GH Actions is faster, e.g.:

![image](https://user-images.githubusercontent.com/12725868/90485273-fb170300-e13f-11ea-8e5a-0f3717a40e81.png)

***

I also think that not only `develop`, but also `master` branch should be protected. As now we can freely commit to `master`.

**Comment by bryanhanson** [comment]
I agree about moving to use GHA only.  Faster or slower is less important.  Removing the extra layers involved with Travis or Appveyor is a plus.

**Comment by bryanhanson** [comment]
Closing, as issue was gradually decided by our actions!
